server:
  port: 8123
  servlet:
    context-path: /api
logging:
  level:
    com.chen.cloudapi_interface: DEBUG
cloud:
  client:
    #为了引入client 直接在配置类中引入调用者的信息配置即可 再在测试类中写个cliet的调用
    access-key: fffb1ccfb419e9deaeec3d3bcbdfe9eb
    secret-key: 562d25c59010bf6038d5db965489733c